name: .NET Build and Test CI

on:
  push:
    branches:
      - master   # Run on push to main branch
  pull_request:
    branches:
      - master   # Run on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Use .NET 8 SDK

    - name: Restore dependencies
      run: dotnet restore NameSorter.sln

    - name: Build the solution
      run: dotnet build NameSorter.sln --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test NameSorter.sln --configuration Release --no-build --verbosity normal
